openapi: 3.0.1
paths:
    /api/atlas/v2/groups/{groupId}/clusters/{clusterName}/outageSimulation:
        delete:
            description: Ends a cluster outage simulation.
            externalDocs:
                description: Cluster Outage Simulation
                url: https://dochub.mongodb.org/core/test-regional-outage
            operationId: endOutageSimulation
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/pretty'
                - $ref: '#/components/parameters/groupId'
                - description: Human-readable label that identifies the cluster that is undergoing outage simulation.
                  in: path
                  name: clusterName
                  required: true
                  schema:
                    maxLength: 64
                    minLength: 1
                    pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]*$
                    type: string
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/ClusterOutageSimulation'
                            x-xgen-version: "2023-01-01"
                    description: OK
                "400":
                    $ref: '#/components/responses/badRequest'
                "401":
                    $ref: '#/components/responses/unauthorized'
                "404":
                    $ref: '#/components/responses/notFound'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: End an Outage Simulation
            tags:
                - Cluster Outage Simulation
            x-xgen-owner-team: Atlas Dedicated
        get:
            description: Returns one outage simulation for one cluster.
            externalDocs:
                description: Cluster Outage Simulation
                url: https://dochub.mongodb.org/core/test-regional-outage
            operationId: getOutageSimulation
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/pretty'
                - $ref: '#/components/parameters/groupId'
                - description: Human-readable label that identifies the cluster that is undergoing outage simulation.
                  in: path
                  name: clusterName
                  required: true
                  schema:
                    maxLength: 64
                    minLength: 1
                    pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]*$
                    type: string
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/ClusterOutageSimulation'
                            x-xgen-version: "2023-01-01"
                    description: OK
                "400":
                    $ref: '#/components/responses/badRequest'
                "401":
                    $ref: '#/components/responses/unauthorized'
                "404":
                    $ref: '#/components/responses/notFound'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Return One Outage Simulation
            tags:
                - Cluster Outage Simulation
            x-xgen-owner-team: Atlas Dedicated
        post:
            description: Starts a cluster outage simulation.
            externalDocs:
                description: Cluster Outage Simulation
                url: https://dochub.mongodb.org/core/test-regional-outage
            operationId: startOutageSimulation
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/pretty'
                - $ref: '#/components/parameters/groupId'
                - description: Human-readable label that identifies the cluster to undergo an outage simulation.
                  in: path
                  name: clusterName
                  required: true
                  schema:
                    maxLength: 64
                    minLength: 1
                    pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]*$
                    type: string
            requestBody:
                content:
                    application/vnd.atlas.2023-01-01+json:
                        schema:
                            $ref: '#/components/schemas/ClusterOutageSimulation'
                description: Describes the outage simulation.
                required: true
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/ClusterOutageSimulation'
                            x-xgen-version: "2023-01-01"
                    description: OK
                "400":
                    $ref: '#/components/responses/badRequest'
                "401":
                    $ref: '#/components/responses/unauthorized'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Start an Outage Simulation
            tags:
                - Cluster Outage Simulation
            x-xgen-owner-team: Atlas Dedicated
