openapi: 3.0.1
paths:
    /api/atlas/v2/groups/{groupId}/cloudProviderAccess:
        get:
            description: Returns all cloud provider access roles with access to the specified project. To use this resource, the requesting API Key must have the Project Owner role.
            operationId: listCloudProviderAccessRoles
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/pretty'
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/CloudProviderAccessRoles'
                            x-xgen-version: "2023-01-01"
                    description: OK
                "404":
                    $ref: '#/components/responses/notFound'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Return All Cloud Provider Access Roles
            tags:
                - Cloud Provider Access
            x-xgen-owner-team: Atlas Dedicated
        post:
            description: Creates one access role for the specified cloud provider. Some MongoDB Cloud features use these cloud provider access roles for authentication. To use this resource, the requesting API Key must have the Project Owner role.
            externalDocs:
                description: Set Up Access to Cloud Providers
                url: https://www.mongodb.com/docs/atlas/security/cloud-provider-access/
            operationId: createCloudProviderAccessRole
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/pretty'
            requestBody:
                content:
                    application/vnd.atlas.2023-01-01+json:
                        schema:
                            $ref: '#/components/schemas/CloudProviderAccessRoleRequest'
                description: Creates one role for the specified cloud provider.
                required: true
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/CloudProviderAccessRole'
                            x-xgen-version: "2023-01-01"
                    description: OK
                "404":
                    $ref: '#/components/responses/notFound'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Create One Cloud Provider Access Role
            tags:
                - Cloud Provider Access
            x-xgen-owner-team: Atlas Dedicated
    /api/atlas/v2/groups/{groupId}/cloudProviderAccess/{cloudProvider}/{roleId}:
        delete:
            description: Revokes access to the specified project for the specified access role. To use this resource, the requesting API Key must have the Project Owner role.
            operationId: deauthorizeCloudProviderAccessRole
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/pretty'
                - description: Human-readable label that identifies the cloud provider of the role to deauthorize.
                  in: path
                  name: cloudProvider
                  required: true
                  schema:
                    enum:
                        - AWS
                        - AZURE
                        - GCP
                    type: string
                - description: Unique 24-hexadecimal digit string that identifies the role.
                  in: path
                  name: roleId
                  required: true
                  schema:
                    maxLength: 24
                    minLength: 24
                    pattern: ^([a-f0-9]{24})$
                    type: string
            responses:
                "204":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            x-xgen-version: "2023-01-01"
                    description: No Content
                "400":
                    $ref: '#/components/responses/badRequest'
                "404":
                    $ref: '#/components/responses/notFound'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Deauthorize One Cloud Provider Access Role
            tags:
                - Cloud Provider Access
            x-xgen-owner-team: Atlas Dedicated
        x-xgen-IPA-exception:
            xgen-IPA-102-path-alternate-resource-name-path-param: API predates IPA validation
    /api/atlas/v2/groups/{groupId}/cloudProviderAccess/{roleId}:
        get:
            description: Returns the access role with the specified id and with access to the specified project. To use this resource, the requesting API Key must have the Project Owner role.
            operationId: getCloudProviderAccessRole
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/pretty'
                - description: Unique 24-hexadecimal digit string that identifies the role.
                  in: path
                  name: roleId
                  required: true
                  schema:
                    maxLength: 24
                    minLength: 24
                    pattern: ^([a-f0-9]{24})$
                    type: string
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/CloudProviderAccessRole'
                            x-xgen-version: "2023-01-01"
                    description: OK
                "404":
                    $ref: '#/components/responses/notFound'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Return specified Cloud Provider Access Role
            tags:
                - Cloud Provider Access
            x-xgen-owner-team: Atlas Dedicated
        patch:
            description: Grants access to the specified project for the specified access role. To use this resource, the requesting API Key must have the Project Owner role. This API endpoint is one step in a procedure to create unified access for MongoDB Cloud services. This is not required for GCP service account access.
            externalDocs:
                description: Set Up Access to Cloud Providers
                url: https://www.mongodb.com/docs/atlas/security/cloud-provider-access/
            operationId: authorizeCloudProviderAccessRole
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/pretty'
                - description: Unique 24-hexadecimal digit string that identifies the role.
                  in: path
                  name: roleId
                  required: true
                  schema:
                    maxLength: 24
                    minLength: 24
                    pattern: ^([a-f0-9]{24})$
                    type: string
            requestBody:
                content:
                    application/vnd.atlas.2023-01-01+json:
                        schema:
                            $ref: '#/components/schemas/CloudProviderAccessRoleRequestUpdate'
                description: Grants access to the specified project for the specified access role.
                required: true
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/CloudProviderAccessRole'
                            x-xgen-version: "2023-01-01"
                    description: OK
                "400":
                    $ref: '#/components/responses/badRequest'
                "404":
                    $ref: '#/components/responses/notFound'
                "409":
                    $ref: '#/components/responses/conflict'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Authorize One Cloud Provider Access Role
            tags:
                - Cloud Provider Access
            x-xgen-owner-team: Atlas Dedicated
