openapi: 3.0.1
paths:
    /api/atlas/v2/groups/{groupId}/flexClusters/{name}/backup/restoreJobs:
        get:
            description: Returns all restore jobs for one flex cluster from the specified project. To use this resource, the requesting API Key must have the Project Owner role.
            operationId: listFlexBackupRestoreJobs
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/includeCount'
                - $ref: '#/components/parameters/itemsPerPage'
                - $ref: '#/components/parameters/pageNum'
                - $ref: '#/components/parameters/pretty'
                - description: Human-readable label that identifies the flex cluster.
                  in: path
                  name: name
                  required: true
                  schema:
                    maxLength: 64
                    minLength: 1
                    pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]*$
                    type: string
            responses:
                "200":
                    content:
                        application/vnd.atlas.2024-11-13+json:
                            schema:
                                $ref: '#/components/schemas/PaginatedApiAtlasFlexBackupRestoreJob20241113View'
                            x-xgen-version: "2024-11-13"
                    description: OK
                "400":
                    $ref: '#/components/responses/badRequest'
                "404":
                    $ref: '#/components/responses/notFound'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Return All Restore Jobs for One Flex Cluster
            tags:
                - Flex Restore Jobs
            x-xgen-owner-team: Atlas Serverless II
        post:
            description: Restores one snapshot of one flex cluster from the specified project. To use this resource, the requesting API Key must have the Project Owner role.
            operationId: createFlexBackupRestoreJob
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/pretty'
                - description: Human-readable label that identifies the flex cluster whose snapshot you want to restore.
                  in: path
                  name: name
                  required: true
                  schema:
                    maxLength: 64
                    minLength: 1
                    pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]*$
                    type: string
            requestBody:
                content:
                    application/vnd.atlas.2024-11-13+json:
                        schema:
                            $ref: '#/components/schemas/FlexBackupRestoreJobCreate20241113'
                description: Restores one snapshot of one flex cluster from the specified project.
                required: true
            responses:
                "200":
                    content:
                        application/vnd.atlas.2024-11-13+json:
                            schema:
                                $ref: '#/components/schemas/FlexBackupRestoreJob20241113'
                            x-xgen-version: "2024-11-13"
                    description: OK
                "400":
                    $ref: '#/components/responses/badRequest'
                "403":
                    $ref: '#/components/responses/forbidden'
                "404":
                    $ref: '#/components/responses/notFound'
                "409":
                    $ref: '#/components/responses/conflict'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Restore One Snapshot of One Flex Cluster
            tags:
                - Flex Restore Jobs
            x-xgen-owner-team: Atlas Serverless II
        x-xgen-IPA-exception:
            xgen-IPA-102-path-alternate-resource-name-path-param: API predates IPA validation
    /api/atlas/v2/groups/{groupId}/flexClusters/{name}/backup/restoreJobs/{restoreJobId}:
        get:
            description: Returns one restore job for one flex cluster from the specified project. To use this resource, the requesting API Key must have the Project Owner role.
            operationId: getFlexBackupRestoreJob
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/pretty'
                - description: Human-readable label that identifies the flex cluster.
                  in: path
                  name: name
                  required: true
                  schema:
                    maxLength: 64
                    minLength: 1
                    pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]*$
                    type: string
                - description: Unique 24-hexadecimal digit string that identifies the restore job to return.
                  in: path
                  name: restoreJobId
                  required: true
                  schema:
                    maxLength: 24
                    minLength: 24
                    pattern: ^([a-f0-9]{24})$
                    type: string
            responses:
                "200":
                    content:
                        application/vnd.atlas.2024-11-13+json:
                            schema:
                                $ref: '#/components/schemas/FlexBackupRestoreJob20241113'
                            x-xgen-version: "2024-11-13"
                    description: OK
                "400":
                    $ref: '#/components/responses/badRequest'
                "404":
                    $ref: '#/components/responses/notFound'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Return One Restore Job for One Flex Cluster
            tags:
                - Flex Restore Jobs
            x-xgen-owner-team: Atlas Serverless II
        x-xgen-IPA-exception:
            xgen-IPA-102-path-alternate-resource-name-path-param: API predates IPA validation
