openapi: 3.0.1
paths:
    /api/atlas/v2/groups/{groupId}/clusters/{clusterName}/backup/tenant/download:
        post:
            description: Requests one snapshot for the specified shared cluster. This resource returns a `snapshotURL` that you can use to download the snapshot. This `snapshotURL` remains active for four hours after you make the request. To use this resource, the requesting API Key must have the Project Owner role.
            operationId: downloadSharedClusterBackup
            parameters:
                - description: Human-readable label that identifies the cluster.
                  in: path
                  name: clusterName
                  required: true
                  schema:
                    maxLength: 64
                    minLength: 1
                    pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]*$
                    type: string
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/pretty'
            requestBody:
                content:
                    application/vnd.atlas.2023-01-01+json:
                        schema:
                            $ref: '#/components/schemas/TenantRestore'
                description: Snapshot to be downloaded.
                required: true
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/TenantRestore'
                            x-xgen-version: "2023-01-01"
                    description: OK
                "400":
                    $ref: '#/components/responses/badRequest'
                "401":
                    $ref: '#/components/responses/unauthorized'
                "403":
                    $ref: '#/components/responses/forbidden'
                "404":
                    $ref: '#/components/responses/notFound'
                "409":
                    $ref: '#/components/responses/conflict'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Download One M2 or M5 Cluster Snapshot
            tags:
                - Shared-Tier Snapshots
            x-xgen-owner-team: Atlas Dedicated
        x-xgen-IPA-exception:
            xgen-IPA-102-path-alternate-resource-name-path-param: API predates IPA validation
            xgen-IPA-104-resource-has-GET: API predates IPA validation
    /api/atlas/v2/groups/{groupId}/clusters/{clusterName}/backup/tenant/snapshots:
        get:
            description: Returns details for all snapshots for the specified shared cluster. To use this resource, the requesting API Key must have the Project Read Only role.
            operationId: listSharedClusterBackups
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/pretty'
                - description: Human-readable label that identifies the cluster.
                  in: path
                  name: clusterName
                  required: true
                  schema:
                    maxLength: 64
                    minLength: 1
                    pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]*$
                    type: string
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/PaginatedTenantSnapshotView'
                            x-xgen-version: "2023-01-01"
                    description: OK
                "400":
                    $ref: '#/components/responses/badRequest'
                "404":
                    $ref: '#/components/responses/notFound'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Return All Snapshots for One M2 or M5 Cluster
            tags:
                - Shared-Tier Snapshots
            x-xgen-owner-team: Atlas Dedicated
        x-xgen-IPA-exception:
            xgen-IPA-102-path-alternate-resource-name-path-param: API predates IPA validation
    /api/atlas/v2/groups/{groupId}/clusters/{clusterName}/backup/tenant/snapshots/{snapshotId}:
        get:
            description: Returns details for one snapshot for the specified shared cluster. To use this resource, the requesting API Key must have the Project Read Only role.
            operationId: getSharedClusterBackup
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/pretty'
                - description: Human-readable label that identifies the cluster.
                  in: path
                  name: clusterName
                  required: true
                  schema:
                    maxLength: 64
                    minLength: 1
                    pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]*$
                    type: string
                - description: Unique 24-hexadecimal digit string that identifies the desired snapshot.
                  in: path
                  name: snapshotId
                  required: true
                  schema:
                    maxLength: 24
                    minLength: 24
                    pattern: ^([a-f0-9]{24})$
                    type: string
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/BackupTenantSnapshot'
                            x-xgen-version: "2023-01-01"
                    description: OK
                "400":
                    $ref: '#/components/responses/badRequest'
                "404":
                    $ref: '#/components/responses/notFound'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Return One Snapshot for One M2 or M5 Cluster
            tags:
                - Shared-Tier Snapshots
            x-xgen-owner-team: Atlas Dedicated
        x-xgen-IPA-exception:
            xgen-IPA-102-path-alternate-resource-name-path-param: API predates IPA validation
