openapi: 3.0.1
paths:
    /api/atlas/v2/groups/{groupId}/customDBRoles/roles:
        get:
            description: Returns all custom roles for the specified project. To use this resource, the requesting API Key must have the Project Read Only role.
            operationId: listCustomDatabaseRoles
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/pretty'
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                items:
                                    $ref: '#/components/schemas/UserCustomDBRole'
                                type: array
                            x-xgen-version: "2023-01-01"
                    description: OK
                "401":
                    $ref: '#/components/responses/unauthorized'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Return All Custom Roles in One Project
            tags:
                - Custom Database Roles
            x-xgen-owner-team: Atlas Dedicated
        post:
            description: Creates one custom role in the specified project. To use this resource, the requesting API Key must have the Project Owner role, Project Stream Processing Owner role, or the Project Database Access Admin role.
            operationId: createCustomDatabaseRole
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/pretty'
            requestBody:
                content:
                    application/vnd.atlas.2023-01-01+json:
                        schema:
                            $ref: '#/components/schemas/UserCustomDBRole'
                description: Creates one custom role in the specified project.
                required: true
            responses:
                "202":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/UserCustomDBRole'
                            x-xgen-version: "2023-01-01"
                    description: Accepted
                "400":
                    $ref: '#/components/responses/badRequest'
                "401":
                    $ref: '#/components/responses/unauthorized'
                "403":
                    $ref: '#/components/responses/forbidden'
                "404":
                    $ref: '#/components/responses/notFound'
                "409":
                    $ref: '#/components/responses/conflict'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Create One Custom Role
            tags:
                - Custom Database Roles
            x-xgen-owner-team: Atlas Dedicated
        x-xgen-IPA-exception:
            xgen-IPA-102-path-alternate-resource-name-path-param: API predates IPA validation
    /api/atlas/v2/groups/{groupId}/customDBRoles/roles/{roleName}:
        delete:
            description: Removes one custom role from the specified project. You can't remove a custom role that would leave one or more child roles with no parent roles or actions. You also can't remove a custom role that would leave one or more database users without roles. To use this resource, the requesting API Key must have the Project Owner role, Project Stream Processing Owner role, or the Project Database Access Admin role.
            operationId: deleteCustomDatabaseRole
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/pretty'
                - description: Human-readable label that identifies the role for the request. This name must be unique for this custom role in this project.
                  in: path
                  name: roleName
                  required: true
                  schema:
                    type: string
            responses:
                "204":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            x-xgen-version: "2023-01-01"
                    description: No Content
                "400":
                    $ref: '#/components/responses/badRequest'
                "401":
                    $ref: '#/components/responses/unauthorized'
                "404":
                    $ref: '#/components/responses/notFound'
                "409":
                    $ref: '#/components/responses/conflict'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Remove One Custom Role from One Project
            tags:
                - Custom Database Roles
            x-xgen-owner-team: Atlas Dedicated
        get:
            description: Returns one custom role for the specified project. To use this resource, the requesting API Key must have the Project Read Only role.
            operationId: getCustomDatabaseRole
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/pretty'
                - description: Human-readable label that identifies the role for the request. This name must be unique for this custom role in this project.
                  in: path
                  name: roleName
                  required: true
                  schema:
                    type: string
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/UserCustomDBRole'
                            x-xgen-version: "2023-01-01"
                    description: OK
                "401":
                    $ref: '#/components/responses/unauthorized'
                "404":
                    $ref: '#/components/responses/notFound'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Return One Custom Role in One Project
            tags:
                - Custom Database Roles
            x-xgen-owner-team: Atlas Dedicated
        patch:
            description: Updates one custom role in the specified project. To use this resource, the requesting API Key must have the Project Owner role, the Project Stream Processing Owner role, or the Project Database Access Admin role.
            operationId: updateCustomDatabaseRole
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/pretty'
                - description: Human-readable label that identifies the role for the request. This name must beunique for this custom role in this project.
                  in: path
                  name: roleName
                  required: true
                  schema:
                    type: string
            requestBody:
                content:
                    application/vnd.atlas.2023-01-01+json:
                        schema:
                            $ref: '#/components/schemas/UpdateCustomDBRole'
                description: Updates one custom role in the specified project.
                required: true
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/UserCustomDBRole'
                            x-xgen-version: "2023-01-01"
                    description: OK
                "400":
                    $ref: '#/components/responses/badRequest'
                "401":
                    $ref: '#/components/responses/unauthorized'
                "403":
                    $ref: '#/components/responses/forbidden'
                "404":
                    $ref: '#/components/responses/notFound'
                "409":
                    $ref: '#/components/responses/conflict'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Update One Custom Role in One Project
            tags:
                - Custom Database Roles
            x-xgen-owner-team: Atlas Dedicated
        x-xgen-IPA-exception:
            xgen-IPA-102-path-alternate-resource-name-path-param: API predates IPA validation
