version: 2
updates:
  - package-ecosystem: gomod
    directory: "/tools/cli"
    schedule:
      interval: weekly
      day: tuesday
    open-pull-requests-limit: 20
    commit-message:
      prefix: "chore"
    reviewers:
      - "mongodb/apix-2"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: tuesday
    commit-message:
      prefix: "chore"
    reviewers:
      - "mongodb/apix-2"
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: tuesday
    commit-message:
      prefix: "chore"
    reviewers:
      - "mongodb/APIx"
