openapi: 3.0.1
paths:
    /api/atlas/v2/groups/{groupId}/pushBasedLogExport:
        delete:
            description: Disables the push-based log export feature by resetting the project level settings to its default configuration.
            operationId: deletePushBasedLogConfiguration
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/pretty'
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            x-xgen-version: "2023-01-01"
                    description: OK
                "400":
                    $ref: '#/components/responses/badRequest'
                "401":
                    $ref: '#/components/responses/unauthorized'
                "403":
                    $ref: '#/components/responses/forbidden'
                "404":
                    $ref: '#/components/responses/notFound'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Disable the push-based log export feature for a project
            tags:
                - Push-Based Log Export
            x-xgen-owner-team: Atlas Dedicated
        get:
            description: Fetches the current project level settings for the push-based log export feature.
            operationId: getPushBasedLogConfiguration
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/pretty'
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/PushBasedLogExportProject'
                            x-xgen-version: "2023-01-01"
                    description: OK
                "401":
                    $ref: '#/components/responses/unauthorized'
                "403":
                    $ref: '#/components/responses/forbidden'
                "404":
                    $ref: '#/components/responses/notFound'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Get the push-based log export configuration for a project
            tags:
                - Push-Based Log Export
            x-xgen-owner-team: Atlas Dedicated
        patch:
            description: Updates the project level settings for the push-based log export feature.
            operationId: updatePushBasedLogConfiguration
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/pretty'
            requestBody:
                content:
                    application/vnd.atlas.2023-01-01+json:
                        schema:
                            $ref: '#/components/schemas/PushBasedLogExportProject'
                        x-xgen-version: "2023-01-01"
                description: The project configuration details. The S3 bucket name, IAM role ID, and prefix path fields are the only fields that may be specified. Fields left unspecified will not be modified.
                required: true
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            x-xgen-version: "2023-01-01"
                    description: OK
                "400":
                    $ref: '#/components/responses/badRequest'
                "401":
                    $ref: '#/components/responses/unauthorized'
                "403":
                    $ref: '#/components/responses/forbidden'
                "404":
                    $ref: '#/components/responses/notFound'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Update the push-based log export feature for a project
            tags:
                - Push-Based Log Export
            x-xgen-owner-team: Atlas Dedicated
        post:
            description: Configures the project level settings for the push-based log export feature.
            operationId: createPushBasedLogConfiguration
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/pretty'
            requestBody:
                content:
                    application/vnd.atlas.2023-01-01+json:
                        schema:
                            $ref: '#/components/schemas/CreatePushBasedLogExportProjectRequest'
                        x-xgen-version: "2023-01-01"
                description: The project configuration details. The S3 bucket name, IAM role ID, and prefix path fields are required.
                required: true
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            x-xgen-version: "2023-01-01"
                    description: OK
                "400":
                    $ref: '#/components/responses/badRequest'
                "401":
                    $ref: '#/components/responses/unauthorized'
                "403":
                    $ref: '#/components/responses/forbidden'
                "404":
                    $ref: '#/components/responses/notFound'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Enable the push-based log export feature for a project
            tags:
                - Push-Based Log Export
            x-xgen-owner-team: Atlas Dedicated
