openapi: 3.0.1
paths:
    /api/atlas/v2/alertConfigs/matchers/fieldNames:
        get:
            description: Get all field names that the `matchers.fieldName` parameter accepts when you create or update an Alert Configuration. You can successfully call this endpoint with any assigned role.
            operationId: listAlertConfigurationMatchersFieldNames
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/pretty'
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                items:
                                    $ref: '#/components/schemas/MatcherFieldView'
                                type: array
                            x-xgen-version: "2023-01-01"
                    description: OK
                "401":
                    $ref: '#/components/responses/unauthorized'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Get All Alert Configuration Matchers Field Names
            tags:
                - Alert Configurations
            x-xgen-owner-team: CAP
        x-xgen-IPA-exception:
            xgen-IPA-102-path-alternate-resource-name-path-param: API predates IPA validation
    /api/atlas/v2/groups/{groupId}/alertConfigs:
        get:
            description: |-
                Returns all alert configurations for one project. These alert configurations apply to any component in the project. Alert configurations define the triggers and notification methods for alerts. To use this resource, the requesting API Key must have the Project Read Only role.

                This resource remains under revision and may change.
            operationId: listAlertConfigurations
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/includeCount'
                - $ref: '#/components/parameters/itemsPerPage'
                - $ref: '#/components/parameters/pageNum'
                - $ref: '#/components/parameters/pretty'
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/PaginatedAlertConfigView'
                            x-xgen-version: "2023-01-01"
                    description: OK
                "401":
                    $ref: '#/components/responses/unauthorized'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Return All Alert Configurations for One Project
            tags:
                - Alert Configurations
            x-xgen-owner-team: CAP
        post:
            description: |-
                Creates one alert configuration for the specified project. Alert configurations define the triggers and notification methods for alerts. To use this resource, the requesting API Key must have the Organization Owner or Project Owner role.

                This resource remains under revision and may change.
            operationId: createAlertConfiguration
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/pretty'
            requestBody:
                content:
                    application/vnd.atlas.2023-01-01+json:
                        schema:
                            $ref: '#/components/schemas/GroupAlertsConfig'
                description: Creates one alert configuration for the specified project.
                required: true
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/GroupAlertsConfig'
                            x-xgen-version: "2023-01-01"
                    description: OK
                "400":
                    $ref: '#/components/responses/badRequest'
                "401":
                    $ref: '#/components/responses/unauthorized'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Create One Alert Configuration in One Project
            tags:
                - Alert Configurations
            x-xgen-owner-team: CAP
    /api/atlas/v2/groups/{groupId}/alertConfigs/{alertConfigId}:
        delete:
            description: |-
                Removes one alert configuration from the specified project. To use this resource, the requesting API Key must have the Organization Owner or Project Owner role.

                This resource remains under revision and may change.
            operationId: deleteAlertConfiguration
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/pretty'
                - description: Unique 24-hexadecimal digit string that identifies the alert configuration. Use the [/alertConfigs](#tag/Alert-Configurations/operation/listAlertConfigurations) endpoint to retrieve all alert configurations to which the authenticated user has access.
                  in: path
                  name: alertConfigId
                  required: true
                  schema:
                    example: 32b6e34b3d91647abb20e7b8
                    maxLength: 24
                    minLength: 24
                    pattern: ^([a-f0-9]{24})$
                    type: string
            responses:
                "204":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            x-xgen-version: "2023-01-01"
                    description: No Content
                "401":
                    $ref: '#/components/responses/unauthorized'
                "404":
                    $ref: '#/components/responses/notFound'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Remove One Alert Configuration from One Project
            tags:
                - Alert Configurations
            x-xgen-owner-team: CAP
        get:
            description: |-
                Returns the specified alert configuration from the specified project. To use this resource, the requesting API Key must have the Project Read Only role.

                This resource remains under revision and may change.
            operationId: getAlertConfiguration
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/pretty'
                - description: Unique 24-hexadecimal digit string that identifies the alert configuration. Use the [/alertConfigs](#tag/Alert-Configurations/operation/listAlertConfigurations) endpoint to retrieve all alert configurations to which the authenticated user has access.
                  in: path
                  name: alertConfigId
                  required: true
                  schema:
                    example: 32b6e34b3d91647abb20e7b8
                    maxLength: 24
                    minLength: 24
                    pattern: ^([a-f0-9]{24})$
                    type: string
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/GroupAlertsConfig'
                            x-xgen-version: "2023-01-01"
                    description: OK
                "401":
                    $ref: '#/components/responses/unauthorized'
                "404":
                    $ref: '#/components/responses/notFound'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Return One Alert Configuration from One Project
            tags:
                - Alert Configurations
            x-xgen-owner-team: CAP
        patch:
            description: |-
                Enables or disables the specified alert configuration in the specified project. The resource enables the specified alert configuration if currently enabled. The resource disables the specified alert configuration if currently disabled. To use this resource, the requesting API Key must have the Organization Owner or Project Owner role.

                **NOTE**: This endpoint updates only the enabled/disabled state for the alert configuration. To update more than just this configuration, see [Update One Alert Configuration](#tag/Alert-Configurations/operation/updateAlertConfiguration).

                This resource remains under revision and may change.
            operationId: toggleAlertConfiguration
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/pretty'
                - description: Unique 24-hexadecimal digit string that identifies the alert configuration that triggered this alert. Use the [/alertConfigs](#tag/Alert-Configurations/operation/listAlertConfigurations) endpoint to retrieve all alert configurations to which the authenticated user has access.
                  in: path
                  name: alertConfigId
                  required: true
                  schema:
                    example: 32b6e34b3d91647abb20e7b8
                    maxLength: 24
                    minLength: 24
                    pattern: ^([a-f0-9]{24})$
                    type: string
            requestBody:
                content:
                    application/vnd.atlas.2023-01-01+json:
                        schema:
                            $ref: '#/components/schemas/AlertsToggle'
                description: Enables or disables the specified alert configuration in the specified project.
                required: true
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/GroupAlertsConfig'
                            x-xgen-version: "2023-01-01"
                    description: OK
                "401":
                    $ref: '#/components/responses/unauthorized'
                "404":
                    $ref: '#/components/responses/notFound'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Toggle One State of One Alert Configuration in One Project
            tags:
                - Alert Configurations
            x-xgen-owner-team: CAP
        put:
            description: |-
                Updates one alert configuration in the specified project. Alert configurations define the triggers and notification methods for alerts. To use this resource, the requesting API Key must have the Organization Owner or Project Owner role.

                **NOTE**: To enable or disable the alert configuration, see [Toggle One State of One Alert Configuration in One Project](#tag/Alert-Configurations/operation/toggleAlertConfiguration).

                This resource remains under revision and may change.
            operationId: updateAlertConfiguration
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/pretty'
                - description: Unique 24-hexadecimal digit string that identifies the alert configuration. Use the [/alertConfigs](#tag/Alert-Configurations/operation/listAlertConfigurations) endpoint to retrieve all alert configurations to which the authenticated user has access.
                  in: path
                  name: alertConfigId
                  required: true
                  schema:
                    example: 32b6e34b3d91647abb20e7b8
                    maxLength: 24
                    minLength: 24
                    pattern: ^([a-f0-9]{24})$
                    type: string
            requestBody:
                content:
                    application/vnd.atlas.2023-01-01+json:
                        schema:
                            $ref: '#/components/schemas/GroupAlertsConfig'
                description: Updates one alert configuration in the specified project.
                required: true
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/GroupAlertsConfig'
                            x-xgen-version: "2023-01-01"
                    description: OK
                "400":
                    $ref: '#/components/responses/badRequest'
                "401":
                    $ref: '#/components/responses/unauthorized'
                "404":
                    $ref: '#/components/responses/notFound'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Update One Alert Configuration for One Project
            tags:
                - Alert Configurations
            x-xgen-owner-team: CAP
    /api/atlas/v2/groups/{groupId}/alerts/{alertId}/alertConfigs:
        get:
            description: |-
                Returns all alert configurations set for the specified alert. To use this resource, the requesting API Key must have the Project Read Only role.

                This resource remains under revision and may change.
            operationId: listAlertConfigurationsByAlertId
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/pretty'
                - $ref: '#/components/parameters/includeCount'
                - $ref: '#/components/parameters/itemsPerPage'
                - $ref: '#/components/parameters/pageNum'
                - description: Unique 24-hexadecimal digit string that identifies the alert. Use the [/alerts](#tag/Alerts/operation/listAlerts) endpoint to retrieve all alerts to which the authenticated user has access.
                  in: path
                  name: alertId
                  required: true
                  schema:
                    maxLength: 24
                    minLength: 24
                    pattern: ^([a-f0-9]{24})$
                    type: string
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/PaginatedAlertConfigView'
                            x-xgen-version: "2023-01-01"
                    description: OK
                "401":
                    $ref: '#/components/responses/unauthorized'
                "404":
                    $ref: '#/components/responses/notFound'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Return All Alert Configurations Set for One Alert
            tags:
                - Alert Configurations
            x-xgen-owner-team: CAP
