openapi: 3.0.1
paths:
    /api/atlas/v2/groups/{groupId}/flexClusters/{name}/backup/download:
        post:
            description: Requests one snapshot for the specified flex cluster. This resource returns a `snapshotURL` that you can use to download the snapshot. This `snapshotURL` remains active for four hours after you make the request. To use this resource, the requesting API Key must have the Project Owner role.
            operationId: downloadFlexBackup
            parameters:
                - description: Human-readable label that identifies the flex cluster.
                  in: path
                  name: name
                  required: true
                  schema:
                    maxLength: 64
                    minLength: 1
                    pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]*$
                    type: string
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/pretty'
            requestBody:
                content:
                    application/vnd.atlas.2024-11-13+json:
                        schema:
                            $ref: '#/components/schemas/FlexBackupSnapshotDownloadCreate20241113'
                description: Snapshot to be downloaded.
                required: true
            responses:
                "200":
                    content:
                        application/vnd.atlas.2024-11-13+json:
                            schema:
                                $ref: '#/components/schemas/FlexBackupRestoreJob20241113'
                            x-xgen-version: "2024-11-13"
                    description: OK
                "400":
                    $ref: '#/components/responses/badRequest'
                "401":
                    $ref: '#/components/responses/unauthorized'
                "403":
                    $ref: '#/components/responses/forbidden'
                "404":
                    $ref: '#/components/responses/notFound'
                "409":
                    $ref: '#/components/responses/conflict'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Download One Flex Cluster Snapshot
            tags:
                - Flex Snapshots
            x-xgen-owner-team: Atlas Serverless II
        x-xgen-IPA-exception:
            xgen-IPA-102-path-alternate-resource-name-path-param: API predates IPA validation
            xgen-IPA-104-resource-has-GET: API predates IPA validation
    /api/atlas/v2/groups/{groupId}/flexClusters/{name}/backup/snapshots:
        get:
            description: Returns all snapshots of one flex cluster from the specified project. To use this resource, the requesting API Key must have the Project Read Only role.
            operationId: listFlexBackups
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/pretty'
                - $ref: '#/components/parameters/includeCount'
                - $ref: '#/components/parameters/itemsPerPage'
                - $ref: '#/components/parameters/pageNum'
                - description: Human-readable label that identifies the flex cluster.
                  in: path
                  name: name
                  required: true
                  schema:
                    maxLength: 64
                    minLength: 1
                    pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]*$
                    type: string
            responses:
                "200":
                    content:
                        application/vnd.atlas.2024-11-13+json:
                            schema:
                                $ref: '#/components/schemas/PaginatedApiAtlasFlexBackupSnapshot20241113View'
                            x-xgen-version: "2024-11-13"
                    description: OK
                "400":
                    $ref: '#/components/responses/badRequest'
                "404":
                    $ref: '#/components/responses/notFound'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Return All Snapshots of One Flex Cluster
            tags:
                - Flex Snapshots
            x-xgen-owner-team: Atlas Serverless II
        x-xgen-IPA-exception:
            xgen-IPA-102-path-alternate-resource-name-path-param: API predates IPA validation
    /api/atlas/v2/groups/{groupId}/flexClusters/{name}/backup/snapshots/{snapshotId}:
        get:
            description: Returns one snapshot of one flex cluster from the specified project. To use this resource, the requesting API Key must have the Project Read Only role.
            operationId: getFlexBackup
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - description: Human-readable label that identifies the flex cluster.
                  in: path
                  name: name
                  required: true
                  schema:
                    maxLength: 64
                    minLength: 1
                    pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]*$
                    type: string
                - description: Unique 24-hexadecimal digit string that identifies the desired snapshot.
                  in: path
                  name: snapshotId
                  required: true
                  schema:
                    example: 32b6e34b3d91647abb20e7b8
                    maxLength: 24
                    minLength: 24
                    pattern: ^([a-f0-9]{24})$
                    type: string
            responses:
                "200":
                    content:
                        application/vnd.atlas.2024-11-13+json:
                            schema:
                                $ref: '#/components/schemas/FlexBackupSnapshot20241113'
                            x-xgen-version: "2024-11-13"
                    description: OK
                "400":
                    $ref: '#/components/responses/badRequest'
                "404":
                    $ref: '#/components/responses/notFound'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Return One Snapshot of One Flex Cluster
            tags:
                - Flex Snapshots
            x-xgen-owner-team: Atlas Serverless II
        x-xgen-IPA-exception:
            xgen-IPA-102-path-alternate-resource-name-path-param: API predates IPA validation
