openapi: 3.0.1
paths:
    /api/atlas/v2/groups/{groupId}/awsCustomDNS:
        get:
            description: Returns the custom DNS configuration for AWS clusters in the specified project. To use this resource, the requesting API Key must have the Project Read Only role.
            operationId: getAwsCustomDns
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/pretty'
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/AWSCustomDNSEnabledView'
                            x-xgen-version: "2023-01-01"
                    description: OK
                "401":
                    $ref: '#/components/responses/unauthorized'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Return One Custom DNS Configuration for Atlas Clusters on AWS
            tags:
                - AWS Clusters DNS
            x-xgen-owner-team: Atlas Dedicated
        patch:
            description: Enables or disables the custom DNS configuration for AWS clusters in the specified project. Enable custom DNS if you use AWS VPC peering and use your own DNS servers. To use this resource, the requesting API Key must have the Project Atlas Admin role.
            operationId: toggleAwsCustomDns
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/pretty'
            requestBody:
                content:
                    application/vnd.atlas.2023-01-01+json:
                        schema:
                            $ref: '#/components/schemas/AWSCustomDNSEnabledView'
                description: Enables or disables the custom DNS configuration for AWS clusters in the specified project.
                required: true
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/AWSCustomDNSEnabledView'
                            x-xgen-version: "2023-01-01"
                    description: OK
                "401":
                    $ref: '#/components/responses/unauthorized'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Toggle State of One Custom DNS Configuration for Atlas Clusters on AWS
            tags:
                - AWS Clusters DNS
            x-xgen-owner-team: Atlas Dedicated
