openapi: 3.0.1
paths:
    /api/atlas/v2/groups/{groupId}/auditLog:
        get:
            description: Returns the auditing configuration for the specified project. The auditing configuration defines the events that MongoDB Cloud records in the audit log. To use this resource, the requesting API Key must have the Project Owner role. This feature isn't available for `M0`, `M2`, `M5`, or serverless clusters.
            operationId: getAuditingConfiguration
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/pretty'
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/AuditLog'
                            x-xgen-version: "2023-01-01"
                    description: OK
                "404":
                    $ref: '#/components/responses/notFound'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Return the Auditing Configuration for One Project
            tags:
                - Auditing
            x-xgen-owner-team: IAM
        patch:
            description: Updates the auditing configuration for the specified project. The auditing configuration defines the events that MongoDB Cloud records in the audit log. To use this resource, the requesting API Key must have the Project Owner role. This feature isn't available for `M0`, `M2`, `M5`, or serverless clusters.
            operationId: updateAuditingConfiguration
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/pretty'
            requestBody:
                content:
                    application/vnd.atlas.2023-01-01+json:
                        schema:
                            $ref: '#/components/schemas/AuditLog'
                description: Updated auditing configuration for the specified project.
                required: true
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/AuditLog'
                            x-xgen-version: "2023-01-01"
                    description: OK
                "400":
                    $ref: '#/components/responses/badRequest'
                "404":
                    $ref: '#/components/responses/notFound'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Update Auditing Configuration for One Project
            tags:
                - Auditing
            x-xgen-owner-team: IAM
