package tools

import (
	"testing"

	"github.com/mongodb/openapi/tools/mcp-server/internal/registry"
	"github.com/spf13/afero"
)

func TestGenerateAliasFromPath(t *testing.T) {
	tests := []struct {
		name     string
		filePath string
		want     string
		wantErr  bool
	}{
		{
			name:     "simple yaml file",
			filePath: "/path/to/api.yaml",
			want:     "api",
			wantErr:  false,
		},
		{
			name:     "simple json file",
			filePath: "/path/to/openapi.json",
			want:     "openapi",
			wantErr:  false,
		},
		{
			name:     "file with hyphen",
			filePath: "petstore-api.yaml",
			want:     "petstore-api",
			wantErr:  false,
		},
		{
			name:     "file with spaces",
			filePath: "Pet Store API.yaml",
			want:     "pet-store-api",
			wantErr:  false,
		},
		{
			name:     "file with uppercase",
			filePath: "PetStoreAPI.yaml",
			want:     "petstoreapi",
			wantErr:  false,
		},
		{
			name:     "file with mixed case and spaces",
			filePath: "MongoDB Atlas API.yaml",
			want:     "mongodb-atlas-api",
			wantErr:  false,
		},
		{
			name:     "file with underscores",
			filePath: "my_awesome_api.yaml",
			want:     "my-awesome-api",
			wantErr:  false,
		},
		{
			name:     "file with numbers",
			filePath: "api-v2.yaml",
			want:     "api-v2",
			wantErr:  false,
		},
		{
			name:     "file with special characters",
			filePath: "api@#$%spec.yaml",
			want:     "api-spec",
			wantErr:  false,
		},
		{
			name:     "file with multiple consecutive special chars",
			filePath: "api___---spec.yaml",
			want:     "api-spec",
			wantErr:  false,
		},
		{
			name:     "file with leading/trailing hyphens",
			filePath: "-api-.yaml",
			want:     "api",
			wantErr:  false,
		},
		{
			name:     "complex real-world example",
			filePath: "/Users/me/projects/MongoDB Atlas Admin API v2.0.yaml",
			want:     "mongodb-atlas-admin-api-v2-0",
			wantErr:  false,
		},
		{
			name:     "file with dots in name",
			filePath: "api.spec.v1.yaml",
			want:     "api-spec-v1",
			wantErr:  false,
		},
		{
			name:     "only special chars (should error)",
			filePath: "@#$%.yaml",
			want:     "",
			wantErr:  true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := generateAliasFromPath(tt.filePath)
			if (err != nil) != tt.wantErr {
				t.Errorf("generateAliasFromPath() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if got != tt.want {
				t.Errorf("generateAliasFromPath() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestIsValidAlias(t *testing.T) {
	tests := []struct {
		name  string
		alias string
		want  bool
	}{
		{"valid simple", "api", true},
		{"valid with hyphen", "my-api", true},
		{"valid with numbers", "api-v2", true},
		{"valid complex", "mongodb-atlas-api-v2", true},
		{"invalid uppercase", "MyAPI", false},
		{"invalid underscore", "my_api", false},
		{"invalid space", "my api", false},
		{"invalid special char", "api@spec", false},
		{"invalid empty", "", false},
		{"invalid just hyphen", "-", true},           // hyphen is allowed
		{"invalid starts with number", "2api", true}, // numbers are allowed
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := isValidAlias(tt.alias); got != tt.want {
				t.Errorf("isValidAlias(%q) = %v, want %v", tt.alias, got, tt.want)
			}
		})
	}
}

func TestHandleLoad_AutoGeneratedAlias(t *testing.T) {
	reg := registry.New()

	// Create a test YAML file
	testFile := createTestOpenAPIFile(t, "test-api.yaml")
	defer cleanupTestFile(t, testFile)

	params := LoadParams{
		FilePath: testFile,
		// No alias - should auto-generate
	}

	result, err := handleLoad(reg, params)
	if err != nil {
		t.Fatalf("handleLoad() failed: %v", err)
	}

	if !result.Success {
		t.Error("result.Success = false, want true")
	}

	if result.Alias != "test-api" {
		t.Errorf("result.Alias = %q, want %q", result.Alias, "test-api")
	}

	// Verify it's in the registry
	entry, err := reg.GetByAlias("test-api")
	if err != nil {
		t.Fatalf("GetByAlias() failed: %v", err)
	}

	if entry.FilePath != testFile {
		t.Errorf("entry.FilePath = %q, want %q", entry.FilePath, testFile)
	}
}

func TestHandleLoad_CustomAlias(t *testing.T) {
	reg := registry.New()

	testFile := createTestOpenAPIFile(t, "api.yaml")
	defer cleanupTestFile(t, testFile)

	params := LoadParams{
		FilePath: testFile,
		Alias:    "my-custom-alias",
	}

	result, err := handleLoad(reg, params)
	if err != nil {
		t.Fatalf("handleLoad() failed: %v", err)
	}

	if result.Alias != "my-custom-alias" {
		t.Errorf("result.Alias = %q, want %q", result.Alias, "my-custom-alias")
	}

	// Verify it's in the registry with custom alias
	_, err = reg.GetByAlias("my-custom-alias")
	if err != nil {
		t.Errorf("GetByAlias() failed: %v", err)
	}
}

func TestHandleLoad_InvalidAlias(t *testing.T) {
	reg := registry.New()

	testFile := createTestOpenAPIFile(t, "api.yaml")
	defer cleanupTestFile(t, testFile)

	params := LoadParams{
		FilePath: testFile,
		Alias:    "Invalid_Alias!", // Contains invalid characters
	}

	_, err := handleLoad(reg, params)
	if err == nil {
		t.Fatal("handleLoad() should fail with invalid alias")
	}
}

func TestHandleLoad_Collision(t *testing.T) {
	reg := registry.New()

	// Load first file
	testFile1 := createTestOpenAPIFile(t, "api1.yaml")
	defer cleanupTestFile(t, testFile1)

	params1 := LoadParams{
		FilePath: testFile1,
		Alias:    "shared-alias",
	}

	_, err := handleLoad(reg, params1)
	if err != nil {
		t.Fatalf("First load failed: %v", err)
	}

	// Try to load different file with same alias
	testFile2 := createTestOpenAPIFile(t, "api2.yaml")
	defer cleanupTestFile(t, testFile2)

	params2 := LoadParams{
		FilePath: testFile2,
		Alias:    "shared-alias",
	}

	_, err = handleLoad(reg, params2)
	if err == nil {
		t.Fatal("handleLoad() should fail with collision error")
	}
}

// Helper: creates a temporary OpenAPI file for testing.
func createTestOpenAPIFile(t *testing.T, filename string) string {
	t.Helper()

	content := `openapi: 3.0.0
info:
  title: Test API
  version: 1.0.0
paths:
  /test:
    get:
      summary: Test endpoint
      responses:
        '200':
          description: Success
`

	tmpFile := t.TempDir() + "/" + filename
	fs := afero.NewOsFs()
	err := afero.WriteFile(fs, tmpFile, []byte(content), 0o600)
	if err != nil {
		t.Fatalf("Failed to create test file: %v", err)
	}

	return tmpFile
}

func cleanupTestFile(t *testing.T, _ string) {
	t.Helper()
	// t.TempDir() handles cleanup automatically
}
