openapi: 3.0.1
paths:
    /api/atlas/v2/groups/{groupId}/clusters/{clusterName}/backup/tenant/restore:
        post:
            description: Restores the specified cluster. MongoDB Cloud limits which clusters can be the target clusters of a restore. The target cluster can't use encryption at rest, run a major release MongoDB version different than the snapshot, or receive client requests during restores. MongoDB Cloud deletes all existing data on the target cluster prior to the restore operation. To use this resource, the requesting API Key must have the Project Owner role.
            operationId: createSharedClusterBackupRestoreJob
            parameters:
                - description: Human-readable label that identifies the cluster.
                  in: path
                  name: clusterName
                  required: true
                  schema:
                    maxLength: 64
                    minLength: 1
                    pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]*$
                    type: string
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/pretty'
            requestBody:
                content:
                    application/vnd.atlas.2023-01-01+json:
                        schema:
                            $ref: '#/components/schemas/TenantRestore'
                description: The restore job details.
                required: true
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/TenantRestore'
                            x-xgen-version: "2023-01-01"
                    description: OK
                "400":
                    $ref: '#/components/responses/badRequest'
                "403":
                    $ref: '#/components/responses/forbidden'
                "404":
                    $ref: '#/components/responses/notFound'
                "409":
                    $ref: '#/components/responses/conflict'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Create One Restore Job from One M2 or M5 Cluster
            tags:
                - Shared-Tier Restore Jobs
            x-xgen-owner-team: Atlas Dedicated
        x-xgen-IPA-exception:
            xgen-IPA-102-path-alternate-resource-name-path-param: API predates IPA validation
            xgen-IPA-104-resource-has-GET: API predates IPA validation
    /api/atlas/v2/groups/{groupId}/clusters/{clusterName}/backup/tenant/restores:
        get:
            description: Returns all restore jobs for the specified M2 or M5 cluster. Restore jobs restore a cluster using a snapshot. To use this resource, the requesting API Key must have the Project Read Only role.
            operationId: listSharedClusterBackupRestoreJobs
            parameters:
                - description: Human-readable label that identifies the cluster.
                  in: path
                  name: clusterName
                  required: true
                  schema:
                    maxLength: 64
                    minLength: 1
                    pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]*$
                    type: string
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/pretty'
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/PaginatedTenantRestoreView'
                            x-xgen-version: "2023-01-01"
                    description: OK
                "400":
                    $ref: '#/components/responses/badRequest'
                "404":
                    $ref: '#/components/responses/notFound'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Return All Restore Jobs for One M2 or M5 Cluster
            tags:
                - Shared-Tier Restore Jobs
            x-xgen-owner-team: Atlas Dedicated
        x-xgen-IPA-exception:
            xgen-IPA-102-path-alternate-resource-name-path-param: API predates IPA validation
    /api/atlas/v2/groups/{groupId}/clusters/{clusterName}/backup/tenant/restores/{restoreId}:
        get:
            description: Returns the specified restore job. To use this resource, the requesting API Key must have the Project Read Only role.
            operationId: getSharedClusterBackupRestoreJob
            parameters:
                - description: Human-readable label that identifies the cluster.
                  in: path
                  name: clusterName
                  required: true
                  schema:
                    maxLength: 64
                    minLength: 1
                    pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]*$
                    type: string
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/pretty'
                - description: Unique 24-hexadecimal digit string that identifies the restore job to return.
                  in: path
                  name: restoreId
                  required: true
                  schema:
                    maxLength: 24
                    minLength: 24
                    pattern: ^([a-f0-9]{24})$
                    type: string
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/TenantRestore'
                            x-xgen-version: "2023-01-01"
                    description: OK
                "400":
                    $ref: '#/components/responses/badRequest'
                "404":
                    $ref: '#/components/responses/notFound'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Return One Restore Job for One M2 or M5 Cluster
            tags:
                - Shared-Tier Restore Jobs
            x-xgen-owner-team: Atlas Dedicated
        x-xgen-IPA-exception:
            xgen-IPA-102-path-alternate-resource-name-path-param: API predates IPA validation
