openapi: 3.0.1
paths:
    /api/atlas/v2/groups/{groupId}/encryptionAtRest:
        get:
            description: |-
                Returns the configuration for encryption at rest using the keys you manage through your cloud provider. MongoDB Cloud encrypts all storage even if you don't use your own key management. This resource requires the requesting API Key to have the Project Owner role.

                **LIMITED TO M10 OR GREATER:** MongoDB Cloud limits this feature to dedicated cluster tiers of M10 and greater.
            operationId: getEncryptionAtRest
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/pretty'
                - $ref: '#/components/parameters/groupId'
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/EncryptionAtRest'
                            x-xgen-version: "2023-01-01"
                    description: OK
                "404":
                    $ref: '#/components/responses/notFound'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Return One Configuration for Encryption at Rest using Customer-Managed Keys for One Project
            tags:
                - Encryption at Rest using Customer Key Management
            x-xgen-owner-team: Atlas Dedicated
        patch:
            description: |-
                Updates the configuration for encryption at rest using the keys you manage through your cloud provider. MongoDB Cloud encrypts all storage even if you don't use your own key management. This resource requires the requesting API Key to have the Project Owner role. This feature isn't available for `M0` free clusters, `M2`, `M5`, or serverless clusters.

                 After you configure at least one Encryption at Rest using a Customer Key Management provider for the MongoDB Cloud project, Project Owners can enable Encryption at Rest using Customer Key Management for each MongoDB Cloud cluster for which they require encryption. The Encryption at Rest using Customer Key Management provider doesn't have to match the cluster cloud service provider. MongoDB Cloud doesn't automatically rotate user-managed encryption keys. Defer to your preferred Encryption at Rest using Customer Key Management provider's documentation and guidance for best practices on key rotation. MongoDB Cloud automatically creates a 90-day key rotation alert when you configure Encryption at Rest using Customer Key Management using your Key Management in an MongoDB Cloud project. MongoDB Cloud encrypts all storage whether or not you use your own key management.
            operationId: updateEncryptionAtRest
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/pretty'
                - $ref: '#/components/parameters/groupId'
            requestBody:
                content:
                    application/vnd.atlas.2023-01-01+json:
                        schema:
                            $ref: '#/components/schemas/EncryptionAtRest'
                description: |-
                    Required parameters depend on whether someone has enabled Encryption at Rest using Customer Key Management:

                    If you have enabled Encryption at Rest using Customer Key Management (CMK), Atlas requires all of the parameters for the desired encryption provider.

                    - To use AWS Key Management Service (KMS), MongoDB Cloud requires all the fields in the **awsKms** object.
                    - To use Azure Key Vault, MongoDB Cloud requires all the fields in the **azureKeyVault** object.
                    - To use Google Cloud Key Management Service (KMS), MongoDB Cloud requires all the fields in the **googleCloudKms** object.

                    If you enabled Encryption at Rest using Customer Key  Management, administrators can pass only the changed fields for the **awsKms**, **azureKeyVault**, or **googleCloudKms** object to update the configuration to this endpoint.
                required: true
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/EncryptionAtRest'
                            x-xgen-version: "2023-01-01"
                    description: OK
                "400":
                    $ref: '#/components/responses/badRequest'
                "403":
                    $ref: '#/components/responses/forbidden'
                "404":
                    $ref: '#/components/responses/notFound'
                "409":
                    $ref: '#/components/responses/conflict'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Update Configuration for Encryption at Rest using Customer-Managed Keys for One Project
            tags:
                - Encryption at Rest using Customer Key Management
            x-xgen-owner-team: Atlas Dedicated
    /api/atlas/v2/groups/{groupId}/encryptionAtRest/{cloudProvider}/privateEndpoints:
        get:
            description: Returns the private endpoints of the specified cloud provider for encryption at rest using customer key management.
            operationId: getEncryptionAtRestPrivateEndpointsForCloudProvider
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/pretty'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/includeCount'
                - $ref: '#/components/parameters/itemsPerPage'
                - $ref: '#/components/parameters/pageNum'
                - description: Human-readable label that identifies the cloud provider for the private endpoints to return.
                  in: path
                  name: cloudProvider
                  required: true
                  schema:
                    enum:
                        - AZURE
                        - AWS
                    type: string
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/PaginatedApiAtlasEARPrivateEndpointView'
                            x-xgen-version: "2023-01-01"
                    description: OK
                "403":
                    $ref: '#/components/responses/forbidden'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Return Private Endpoints of a Cloud Provider for Encryption at Rest Using Customer Key Management for One Project
            tags:
                - Encryption at Rest using Customer Key Management
            x-xgen-owner-team: Atlas Dedicated
        post:
            description: Creates a private endpoint in the specified region for encryption at rest using customer key management.
            operationId: createEncryptionAtRestPrivateEndpoint
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/pretty'
                - $ref: '#/components/parameters/groupId'
                - description: Human-readable label that identifies the cloud provider for the private endpoint to create.
                  in: path
                  name: cloudProvider
                  required: true
                  schema:
                    enum:
                        - AZURE
                        - AWS
                    type: string
            requestBody:
                content:
                    application/vnd.atlas.2023-01-01+json:
                        schema:
                            $ref: '#/components/schemas/EARPrivateEndpoint'
                description: Creates a private endpoint in the specified region.
                required: true
            responses:
                "202":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/EARPrivateEndpoint'
                            x-xgen-version: "2023-01-01"
                    description: Accepted
                "403":
                    $ref: '#/components/responses/forbidden'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Create One Private Endpoint in a Specified Region for Encryption at Rest Using Customer Key Management
            tags:
                - Encryption at Rest using Customer Key Management
            x-xgen-owner-team: Atlas Dedicated
    /api/atlas/v2/groups/{groupId}/encryptionAtRest/{cloudProvider}/privateEndpoints/{endpointId}:
        delete:
            description: Deletes one private endpoint, identified by its ID, for encryption at rest using Customer Key Management.
            operationId: requestEncryptionAtRestPrivateEndpointDeletion
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/pretty'
                - $ref: '#/components/parameters/groupId'
                - description: Human-readable label that identifies the cloud provider of the private endpoint to delete.
                  in: path
                  name: cloudProvider
                  required: true
                  schema:
                    enum:
                        - AZURE
                        - AWS
                    type: string
                - description: Unique 24-hexadecimal digit string that identifies the private endpoint to delete.
                  in: path
                  name: endpointId
                  required: true
                  schema:
                    maxLength: 24
                    minLength: 24
                    pattern: ^([a-f0-9]{24})$
                    type: string
            responses:
                "204":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/NoBody'
                            x-xgen-version: "2023-01-01"
                    description: This endpoint does not return a response body.
                "403":
                    $ref: '#/components/responses/forbidden'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Delete Private Endpoint for Encryption at Rest Using Customer Key Management
            tags:
                - Encryption at Rest using Customer Key Management
            x-xgen-owner-team: Atlas Dedicated
        get:
            description: Returns one private endpoint, identified by its ID, for encryption at rest using Customer Key Management.
            operationId: getEncryptionAtRestPrivateEndpoint
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/pretty'
                - $ref: '#/components/parameters/groupId'
                - description: Human-readable label that identifies the cloud provider of the private endpoint.
                  in: path
                  name: cloudProvider
                  required: true
                  schema:
                    enum:
                        - AZURE
                        - AWS
                    type: string
                - description: Unique 24-hexadecimal digit string that identifies the private endpoint.
                  in: path
                  name: endpointId
                  required: true
                  schema:
                    maxLength: 24
                    minLength: 24
                    pattern: ^([a-f0-9]{24})$
                    type: string
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/EARPrivateEndpoint'
                            x-xgen-version: "2023-01-01"
                    description: OK
                "403":
                    $ref: '#/components/responses/forbidden'
                "404":
                    $ref: '#/components/responses/notFound'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Return One Private Endpoint for Encryption at Rest Using Customer Key Management
            tags:
                - Encryption at Rest using Customer Key Management
            x-xgen-owner-team: Atlas Dedicated
