openapi: 3.0.1
paths:
    /api/atlas/v2/groups/{groupId}/flexClusters:
        get:
            description: Returns details for all flex clusters in the specified project. To use this resource, the requesting API Key must have the Project Read Only role.
            operationId: listFlexClusters
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/includeCount'
                - $ref: '#/components/parameters/itemsPerPage'
                - $ref: '#/components/parameters/pageNum'
                - $ref: '#/components/parameters/pretty'
            responses:
                "200":
                    content:
                        application/vnd.atlas.2024-11-13+json:
                            schema:
                                $ref: '#/components/schemas/PaginatedFlexClusters20241113'
                            x-xgen-version: "2024-11-13"
                    description: OK
                "409":
                    $ref: '#/components/responses/conflict'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Return All Flex Clusters from One Project
            tags:
                - Flex Clusters
            x-xgen-owner-team: Atlas Serverless II
        post:
            description: Creates one flex cluster in the specified project. To use this resource, the requesting API Key must have the Project Owner role.
            operationId: createFlexCluster
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/pretty'
            requestBody:
                content:
                    application/vnd.atlas.2024-11-13+json:
                        schema:
                            $ref: '#/components/schemas/FlexClusterDescriptionCreate20241113'
                description: Create One Flex Cluster in One Project.
                required: true
            responses:
                "201":
                    content:
                        application/vnd.atlas.2024-11-13+json:
                            schema:
                                $ref: '#/components/schemas/FlexClusterDescription20241113'
                            x-xgen-version: "2024-11-13"
                    description: Created
                "400":
                    $ref: '#/components/responses/badRequest'
                "402":
                    $ref: '#/components/responses/paymentRequired'
                "409":
                    $ref: '#/components/responses/conflict'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Create One Flex Cluster in One Project
            tags:
                - Flex Clusters
            x-xgen-owner-team: Atlas Serverless II
    /api/atlas/v2/groups/{groupId}/flexClusters/{name}:
        delete:
            description: Removes one flex cluster from the specified project. The flex cluster must have termination protection disabled in order to be deleted. To use this resource, the requesting API Key must have the Project Owner role.
            operationId: deleteFlexCluster
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/pretty'
                - $ref: '#/components/parameters/groupId'
                - description: Human-readable label that identifies the flex cluster.
                  in: path
                  name: name
                  required: true
                  schema:
                    maxLength: 64
                    minLength: 1
                    pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]*$
                    type: string
            responses:
                "204":
                    content:
                        application/vnd.atlas.2024-11-13+json:
                            schema:
                                $ref: '#/components/schemas/NoBody'
                            x-xgen-version: "2024-11-13"
                    description: This endpoint does not return a response body.
                "400":
                    $ref: '#/components/responses/badRequest'
                "404":
                    $ref: '#/components/responses/notFound'
                "409":
                    $ref: '#/components/responses/conflict'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Remove One Flex Cluster from One Project
            tags:
                - Flex Clusters
            x-xgen-owner-team: Atlas Serverless II
        get:
            description: Returns details for one flex cluster in the specified project. To use this resource, the requesting API Key must have the Project Read Only role.
            operationId: getFlexCluster
            parameters:
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/pretty'
                - description: Human-readable label that identifies the flex cluster.
                  in: path
                  name: name
                  required: true
                  schema:
                    maxLength: 64
                    minLength: 1
                    pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]*$
                    type: string
            responses:
                "200":
                    content:
                        application/vnd.atlas.2024-11-13+json:
                            schema:
                                $ref: '#/components/schemas/FlexClusterDescription20241113'
                            x-xgen-version: "2024-11-13"
                    description: OK
                "400":
                    $ref: '#/components/responses/badRequest'
                "404":
                    $ref: '#/components/responses/notFound'
                "409":
                    $ref: '#/components/responses/conflict'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Return One Flex Cluster from One Project
            tags:
                - Flex Clusters
            x-xgen-owner-team: Atlas Serverless II
        patch:
            description: Updates one flex cluster in the specified project. To use this resource, the requesting API Key must have the Project Owner role.
            operationId: updateFlexCluster
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/pretty'
                - description: Human-readable label that identifies the flex cluster.
                  in: path
                  name: name
                  required: true
                  schema:
                    maxLength: 64
                    minLength: 1
                    pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]*$
                    type: string
            requestBody:
                content:
                    application/vnd.atlas.2024-11-13+json:
                        schema:
                            $ref: '#/components/schemas/FlexClusterDescriptionUpdate20241113'
                description: Update One Flex Cluster in One Project.
                required: true
            responses:
                "200":
                    content:
                        application/vnd.atlas.2024-11-13+json:
                            schema:
                                $ref: '#/components/schemas/FlexClusterDescription20241113'
                            x-xgen-version: "2024-11-13"
                    description: OK
                "400":
                    $ref: '#/components/responses/badRequest'
                "402":
                    $ref: '#/components/responses/paymentRequired'
                "409":
                    $ref: '#/components/responses/conflict'
            summary: Update One Flex Cluster in One Project
            tags:
                - Flex Clusters
            x-xgen-owner-team: Atlas Serverless II
    /api/atlas/v2/groups/{groupId}/flexClusters:tenantUpgrade:
        post:
            description: Upgrades a flex cluster to a dedicated cluster (M10+) in the specified project. To use this resource, the requesting API key must have the Project Cluster Manager role.
            operationId: upgradeFlexCluster
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/groupId'
                - $ref: '#/components/parameters/pretty'
            requestBody:
                content:
                    application/vnd.atlas.2024-11-13+json:
                        schema:
                            $ref: '#/components/schemas/AtlasTenantClusterUpgradeRequest20240805'
                description: Details of the flex cluster upgrade in the specified project.
                required: true
            responses:
                "200":
                    content:
                        application/vnd.atlas.2024-11-13+json:
                            schema:
                                $ref: '#/components/schemas/FlexClusterDescription20241113'
                            x-xgen-version: "2024-11-13"
                    description: OK
                "400":
                    $ref: '#/components/responses/badRequest'
                "401":
                    $ref: '#/components/responses/unauthorized'
                "402":
                    $ref: '#/components/responses/paymentRequired'
                "403":
                    $ref: '#/components/responses/forbidden'
                "409":
                    $ref: '#/components/responses/conflict'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Upgrade One Flex Cluster
            tags:
                - Flex Clusters
            x-xgen-owner-team: Atlas Serverless II
