openapi: 3.0.1
paths:
    /api/atlas/v2:
        get:
            description: This resource returns information about the MongoDB application along with API key meta data.
            operationId: getSystemStatus
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/pretty'
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/SystemStatus'
                            x-xgen-version: "2023-01-01"
                    description: OK
                "401":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ApiError'
                    description: Unauthorized.
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Return the status of this MongoDB application
            tags:
                - Root
            x-xgen-owner-team: apix
    /api/atlas/v2/unauth/controlPlaneIPAddresses:
        get:
            description: Returns all control plane IP addresses.
            operationId: returnAllControlPlaneIpAddresses
            parameters:
                - $ref: '#/components/parameters/envelope'
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-11-15+json:
                            schema:
                                $ref: '#/components/schemas/ControlPlaneIPAddresses'
                            x-xgen-version: "2023-11-15"
                    description: OK
                "500":
                    $ref: '#/components/responses/internalServerError'
            security: []
            summary: Return All Control Plane IP Addresses
            tags:
                - Root
            x-xgen-owner-team: Atlas Clusters Security II
