# https://meta.stoplight.io/docs/spectral/cb95cf0d26b83-core-functions
extends:
  - https://raw.githubusercontent.com/mongodb/openapi/a3dd7046e8dccd24bb0eb9ccc9ad8c3e39f47685/tools/spectral/ipa/ipa-spectral.yaml

overrides:
  - files:
      - '**#/components/schemas/DataLakeDatabaseDataSourceSettings' # external field, to be covered by CLOUDP-293178
      - '**#/components/schemas/DataLakeAtlasStoreReadPreference' # external field, to be covered by CLOUDP-293178
    rules:
      xgen-IPA-123-enum-values-must-be-upper-snake-case: 'off'
  - files:
      - '**#/components/schemas/DataLakeAtlasStoreInstance' # external field, to be covered by CLOUDP-293178
    rules:
      xgen-IPA-112-avoid-project-field-names: 'off'
  - files:
      - '**#/components/schemas/ClusterProviderSettings/properties/providerName' # dynamic field which can't be documented
      - '**#/components/schemas/DataLakeStoreSettings/properties/provider' # external field, to be covered by CLOUDP-293178
    rules:
      xgen-IPA-117-description: 'off'
  - files:
      - '**#/components/schemas/DataLakeAzureBlobStore' # external field, to be covered by CLOUDP-293178
      - '**#/components/schemas/AdvancedClusterDescription/properties/mongoDBEmployeeAccessGrant' # unable to document exceptions, to be covered by CLOUDP-308286
      - '**#/components/schemas/AtlasTenantClusterUpgradeRequest20240805/properties/mongoDBEmployeeAccessGrant' # unable to document exceptions, to be covered by CLOUDP-308286
      - '**#/components/schemas/ClusterDescription20240805/properties/mongoDBEmployeeAccessGrant' # unable to document exceptions, to be covered by CLOUDP-308286
      - '**#/components/schemas/LegacyAtlasCluster/properties/mongoDBEmployeeAccessGrant' # unable to document exceptions, to be covered by CLOUDP-308286
      - '**#/components/schemas/LegacyAtlasTenantClusterUpgradeRequest/properties/mongoDBEmployeeAccessGrant' # unable to document exceptions, to be covered by CLOUDP-308286
      - '**#/components/schemas/AdvancedAutoScalingSettings/properties/diskGB' # unable to document exceptions, to be covered by CLOUDP-308286
      - '**#/components/schemas/UserSecurity/properties/customerX509' # unable to document exceptions, to be covered by CLOUDP-308286
    rules:
      xgen-IPA-112-field-names-are-camel-case: 'off'
  - files:
      - '**#/components/schemas/DataLakeS3StoreSettings/allOf/1/properties/additionalStorageClasses' # unable to document exceptions, to be covered by CLOUDP-293178
      - '**#/components/schemas/DataLakeDatabaseDataSourceSettings/properties/databaseRegex' # unable to document exceptions, to be covered by CLOUDP-293178
      - '**#/components/schemas/DataLakeDatabaseDataSourceSettings/properties/collectionRegex' # unable to document exceptions, to be covered by CLOUDP-293178
    rules:
      xgen-IPA-117-description-should-not-use-inline-links: 'off'