// Code generated by go generate; DO NOT EDIT.
// Source: tools/spectral/ipa/rulesets/functions/utils/legacyLongRunningOperations.json
//
// Generated by this command:
//
//	go run ./gen

package merge

// legacyLongRunningOperationIDs is the set of operations returning HTTP 202 that
// predate IPA-132 and do not follow the long-running operation contract.
var legacyLongRunningOperationIDs = map[string]struct{}{
	"acceptGroupStreamVpcPeeringConnection":      {},
	"createGroupClusterIndexRollingIndex":        {},
	"createGroupCustomDbRoleRole":                {},
	"createGroupEncryptionAtRestPrivateEndpoint": {},
	"createOrgBillingCostExplorerUsageProcess":   {},
	"cutoverGroupLiveMigration":                  {},
	"deleteGroupCluster":                         {},
	"deleteGroupClusterOverloadSimulation":       {},
	"deleteGroupPeer":                            {},
	"deleteGroupStreamConnection":                {},
	"deleteGroupStreamPrivateLinkConnection":     {},
	"deleteGroupStreamVpcPeeringConnection":      {},
	"deleteGroupStreamWorkspace":                 {},
	"deleteGroupUserSecurityLdapUserToDnMapping": {},
	"disableGroupUserSecurityCustomerX509":       {},
	"rejectGroupStreamVpcPeeringConnection":      {},
	"updateGroupUserSecurity":                    {},
}
