name: 'Code Health FOAS Library'
on:
  push:
    branches:
      - main
    paths:
      - 'tools/foas/**'
      - '.github/workflows/code-health-foas-lib.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'tools/foas/**'
      - '.github/workflows/code-health-foas-lib.yml'
  workflow_dispatch: {}
  workflow_call: {}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
    - name: Install Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16
      with:
        go-version-file: 'tools/foas/go.mod'
    - name: Build library
      working-directory: tools/foas
      run: make build
  unit-tests:
    needs: build
    env:
      COVERAGE: coverage.out
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16
        with:
          go-version-file: 'tools/foas/go.mod'
      - name: Run unit tests
        working-directory: tools/foas
        run: make unit-test
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          sparse-checkout: |
            .github
            tools
      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16
        with:
          go-version-file: 'tools/foas/go.mod'
          cache: false # see https://github.com/golangci/golangci-lint-action/issues/807
      - name: golangci-lint
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee
        with:
          version: v2.10.1
          working-directory: tools/foas
