name: IPA Validations Release
on:
  workflow_call:
    secrets: # all secrets are passed explicitly in this workflow
      aws_access_key:
        required: true
      aws_secret_key:
        required: true
      aws_s3_bucket_prefix:
        required: true
  workflow_dispatch:
permissions:
  issues: write

jobs:
  release-IPA-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install npm dependencies
        run: npm install

      - name: Check last Changelog Entry
        id: check_last_run
        run: |
          last_run_date=$(< changelog/changelog.json jq '.[0].date')
          today=$(date +%F)
          echo "last_run_date=${last_run_date}"
          echo "today=${today}"
          if [[ "${last_run_date}" == "${today}" ]]; then
             echo "skip_release='true'" >> "${GITHUB_OUTPUT}"
          else
             echo "skip_release='false'" >> "${GITHUB_OUTPUT}"
          fi

      - name: Run Metric Collection Job
        working-directory: ./tools/spectral/ipa/metrics
        run: node metricCollection.js

      - name: Dump Metric Collection Job Data to S3
        working-directory: ./tools/spectral/ipa/metrics
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.aws_access_key}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}
          S3_BUCKET_PREFIX: ${{ secrets.aws_s3_bucket_prefix }}
        run: node dataDump.js

