name: Publish IPA Validation Framework Package

on:
  push:
    branches:
      - main
    paths:
      - 'tools/spectral/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Changelog up-to-date
      - run: |
          npm run gen-ipa-changelog
          if [[ -n $(git status --porcelain) ]]; then
            echo "Changelog not up to date, please run 'npm run gen-ipa-changelog' from tools/spectral and commit the changes"
            exit 1
          fi
          exit 0
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - run: npm ci
      - run: npm test
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: "tools/spectral/package.json"