openapi: 3.0.1
paths:
    /api/atlas/v2/groups/{groupId}/clusters/{clusterName}/globalWrites:
        get:
            description: Returns one managed namespace within the specified global cluster. A managed namespace identifies a collection using the database name, the dot separator, and the collection name. To use this resource, the requesting API Key must have the Project Read Only role.
            externalDocs:
                description: Global Clusters
                url: https://www.mongodb.com/docs/atlas/global-clusters/
            operationId: getManagedNamespace
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/pretty'
                - $ref: '#/components/parameters/groupId'
                - description: Human-readable label that identifies this cluster.
                  in: path
                  name: clusterName
                  required: true
                  schema:
                    maxLength: 64
                    minLength: 1
                    pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]*$
                    type: string
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/GeoSharding'
                            x-sunset: "2025-06-01"
                            x-xgen-version: "2023-01-01"
                        application/vnd.atlas.2023-02-01+json:
                            schema:
                                $ref: '#/components/schemas/GeoSharding'
                            x-sunset: "2026-03-01"
                            x-xgen-version: "2023-02-01"
                        application/vnd.atlas.2024-08-05+json:
                            schema:
                                $ref: '#/components/schemas/GeoSharding20240805'
                            x-xgen-version: "2024-08-05"
                    description: OK
                "401":
                    $ref: '#/components/responses/unauthorized'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Return One Managed Namespace in One Global Cluster
            tags:
                - Global Clusters
            x-xgen-owner-team: Atlas Dedicated
    /api/atlas/v2/groups/{groupId}/clusters/{clusterName}/globalWrites/customZoneMapping:
        delete:
            description: Removes all custom zone mappings for the specified global cluster. A custom zone mapping matches one ISO 3166-2 location code to a zone in your global cluster. Removing the custom zone mappings restores the default mapping. By default, MongoDB Cloud maps each location code to the closest geographical zone. To use this resource, the requesting API Key must have the Project Owner role.
            externalDocs:
                description: Global Clusters
                url: https://www.mongodb.com/docs/atlas/global-clusters/
            operationId: deleteAllCustomZoneMappings
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/pretty'
                - $ref: '#/components/parameters/groupId'
                - description: Human-readable label that identifies this cluster.
                  in: path
                  name: clusterName
                  required: true
                  schema:
                    maxLength: 64
                    minLength: 1
                    pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]*$
                    type: string
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/GeoSharding'
                            x-sunset: "2025-06-01"
                            x-xgen-version: "2023-01-01"
                        application/vnd.atlas.2023-02-01+json:
                            schema:
                                $ref: '#/components/schemas/GeoSharding'
                            x-sunset: "2026-03-01"
                            x-xgen-version: "2023-02-01"
                        application/vnd.atlas.2024-08-05+json:
                            schema:
                                $ref: '#/components/schemas/GeoSharding20240805'
                            x-xgen-version: "2024-08-05"
                    description: OK
                "401":
                    $ref: '#/components/responses/unauthorized'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Remove All Custom Zone Mappings from One Global Cluster
            tags:
                - Global Clusters
            x-xgen-owner-team: Atlas Dedicated
        post:
            description: Creates one custom zone mapping for the specified global cluster. A custom zone mapping matches one ISO 3166-2 location code to a zone in your global cluster. By default, MongoDB Cloud maps each location code to the closest geographical zone. To use this resource, the requesting API Key must have the Project Owner role.
            externalDocs:
                description: Global Clusters
                url: https://www.mongodb.com/docs/atlas/global-clusters/
            operationId: createCustomZoneMapping
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/pretty'
                - $ref: '#/components/parameters/groupId'
                - description: Human-readable label that identifies this cluster.
                  in: path
                  name: clusterName
                  required: true
                  schema:
                    maxLength: 64
                    minLength: 1
                    pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]*$
                    type: string
            requestBody:
                content:
                    application/vnd.atlas.2023-01-01+json:
                        schema:
                            $ref: '#/components/schemas/CustomZoneMappings'
                    application/vnd.atlas.2023-02-01+json:
                        schema:
                            $ref: '#/components/schemas/CustomZoneMappings'
                    application/vnd.atlas.2024-08-05+json:
                        schema:
                            $ref: '#/components/schemas/CustomZoneMappings'
                        x-xgen-version: "2024-08-05"
                description: Custom zone mapping to add to the specified global cluster.
                required: true
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/GeoSharding'
                            x-sunset: "2025-06-01"
                            x-xgen-version: "2023-01-01"
                        application/vnd.atlas.2023-02-01+json:
                            schema:
                                $ref: '#/components/schemas/GeoSharding'
                            x-sunset: "2026-03-01"
                            x-xgen-version: "2023-02-01"
                        application/vnd.atlas.2024-08-05+json:
                            schema:
                                $ref: '#/components/schemas/GeoSharding20240805'
                            x-xgen-version: "2024-08-05"
                    description: OK
                "400":
                    $ref: '#/components/responses/badRequest'
                "401":
                    $ref: '#/components/responses/unauthorized'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Add One Entry to One Custom Zone Mapping
            tags:
                - Global Clusters
            x-xgen-owner-team: Atlas Dedicated
        x-xgen-IPA-exception:
            xgen-IPA-102-path-alternate-resource-name-path-param: API predates IPA validation
            xgen-IPA-104-resource-has-GET: API predates IPA validation
    /api/atlas/v2/groups/{groupId}/clusters/{clusterName}/globalWrites/managedNamespaces:
        delete:
            description: Removes one managed namespace within the specified global cluster. A managed namespace identifies a collection using the database name, the dot separator, and the collection name. Deleting a managed namespace does not remove the associated collection or data. To use this resource, the requesting API Key must have the Project Data Access Admin role.
            externalDocs:
                description: Global Clusters
                url: https://www.mongodb.com/docs/atlas/global-clusters/
            operationId: deleteManagedNamespace
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/pretty'
                - description: Human-readable label that identifies this cluster.
                  in: path
                  name: clusterName
                  required: true
                  schema:
                    maxLength: 64
                    minLength: 1
                    pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]*$
                    type: string
                - $ref: '#/components/parameters/groupId'
                - description: Human-readable label that identifies the database that contains the collection.
                  in: query
                  name: db
                  schema:
                    type: string
                - description: Human-readable label that identifies the collection associated with the managed namespace.
                  in: query
                  name: collection
                  schema:
                    type: string
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/GeoSharding'
                            x-sunset: "2025-06-01"
                            x-xgen-version: "2023-01-01"
                        application/vnd.atlas.2023-02-01+json:
                            schema:
                                $ref: '#/components/schemas/GeoSharding'
                            x-sunset: "2026-03-01"
                            x-xgen-version: "2023-02-01"
                        application/vnd.atlas.2024-08-05+json:
                            schema:
                                $ref: '#/components/schemas/GeoSharding20240805'
                            x-xgen-version: "2024-08-05"
                    description: OK
                "400":
                    $ref: '#/components/responses/badRequest'
                "401":
                    $ref: '#/components/responses/unauthorized'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Remove One Managed Namespace from One Global Cluster
            tags:
                - Global Clusters
            x-xgen-owner-team: Atlas Dedicated
        post:
            description: Creates one managed namespace within the specified global cluster. A managed namespace identifies a collection using the database name, the dot separator, and the collection name. To use this resource, the requesting API Key must have the Project Data Access Admin role.
            externalDocs:
                description: Global Clusters
                url: https://www.mongodb.com/docs/atlas/global-clusters/
            operationId: createManagedNamespace
            parameters:
                - $ref: '#/components/parameters/envelope'
                - $ref: '#/components/parameters/pretty'
                - $ref: '#/components/parameters/groupId'
                - description: Human-readable label that identifies this cluster.
                  in: path
                  name: clusterName
                  required: true
                  schema:
                    maxLength: 64
                    minLength: 1
                    pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]*$
                    type: string
            requestBody:
                content:
                    application/vnd.atlas.2023-01-01+json:
                        schema:
                            $ref: '#/components/schemas/ManagedNamespaces'
                    application/vnd.atlas.2023-02-01+json:
                        schema:
                            $ref: '#/components/schemas/ManagedNamespaces'
                    application/vnd.atlas.2024-08-05+json:
                        schema:
                            $ref: '#/components/schemas/ManagedNamespaces'
                        x-xgen-version: "2024-08-05"
                description: Managed namespace to create within the specified global cluster.
                required: true
            responses:
                "200":
                    content:
                        application/vnd.atlas.2023-01-01+json:
                            schema:
                                $ref: '#/components/schemas/GeoSharding'
                            x-sunset: "2025-06-01"
                            x-xgen-version: "2023-01-01"
                        application/vnd.atlas.2023-02-01+json:
                            schema:
                                $ref: '#/components/schemas/GeoSharding'
                            x-sunset: "2026-03-01"
                            x-xgen-version: "2023-02-01"
                        application/vnd.atlas.2024-08-05+json:
                            schema:
                                $ref: '#/components/schemas/GeoSharding20240805'
                            x-xgen-version: "2024-08-05"
                    description: OK
                "400":
                    $ref: '#/components/responses/badRequest'
                "401":
                    $ref: '#/components/responses/unauthorized'
                "405":
                    $ref: '#/components/responses/methodNotAllowed'
                "500":
                    $ref: '#/components/responses/internalServerError'
            summary: Create One Managed Namespace in One Global Cluster
            tags:
                - Global Clusters
            x-xgen-owner-team: Atlas Dedicated
        x-xgen-IPA-exception:
            xgen-IPA-102-path-alternate-resource-name-path-param: API predates IPA validation
            xgen-IPA-104-resource-has-GET: API predates IPA validation
